package io.github.mufasa1976.spring.test.softwareday;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.mufasa1976.spring.test.softwareday.entities.Person;
import io.github.mufasa1976.spring.test.softwareday.repositories.PersonRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.EntityManager;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.springframework.http.MediaType.APPLICATION_JSON_UTF8;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@DisplayName("Test the REST-Interface of Persons")
class PersonRestControllerTest {
  @Autowired
  private MockMvc restControllerWeb;

  @Autowired
  private PersonRepository personRepository;

  @Autowired
  private ObjectMapper objectMapper;

  @Autowired
  private EntityManager entityManager;

  @Test
  @DisplayName("get all Persons and expect exactly 3 Persons")
  void getAll_OK() throws Exception {
    restControllerWeb.perform(get("/api/persons"))
                     .andExpect(status().isOk())
                     .andExpect(content().contentType(APPLICATION_JSON_UTF8))
                     .andExpect(jsonPath("$").isArray())
                     .andExpect(jsonPath("*", hasSize(3)))
                     .andExpect(jsonPath("[0].id").value(is(1)))
                     .andExpect(jsonPath("[0].lastName").value(is("Stadler")))
                     .andExpect(jsonPath("[0].firstName").value(is("Erich")))
                     .andExpect(jsonPath("[1].id").value(is(2)))
                     .andExpect(jsonPath("[1].lastName").value(is("Tuma")))
                     .andExpect(jsonPath("[1].firstName").value(is("Heinz")))
                     .andExpect(jsonPath("[2].id").value(is(3)))
                     .andExpect(jsonPath("[2].lastName").value(is("Fleischmann")))
                     .andExpect(jsonPath("[2].firstName").value(is("Peter")));
  }

  @Test
  @DisplayName("remove all Persons from the Database and expect none are found")
  @Transactional
  void getAll_OK_noDataFound() throws Exception {
    personRepository.deleteAll();

    restControllerWeb.perform(get("/api/persons"))
                     .andExpect(status().isOk())
                     .andExpect(content().contentType(APPLICATION_JSON_UTF8))
                     .andExpect(jsonPath("$").isArray())
                     .andExpect(jsonPath("$").isEmpty());
  }

  @Test
  @DisplayName("Get Person with ID 1 and expect its Name is Erich Stadler")
  void getOneById_OK() throws Exception {
    restControllerWeb.perform(get("/api/persons/1"))
                     .andExpect(status().isOk())
                     .andExpect(content().contentType(APPLICATION_JSON_UTF8))
                     .andExpect(jsonPath("id").value(is(1)))
                     .andExpect(jsonPath("lastName").value(is("Stadler")))
                     .andExpect(jsonPath("firstName").value(is("Erich")));
  }

  @Test
  @DisplayName("Get Person with Id 9999999999 and expect none has been found")
  void getOneById_NOK_notFound() throws Exception {
    restControllerWeb.perform(get("/api/persons/9999999999"))
                     .andExpect(status().isNotFound());
  }

  @Test
  @DisplayName("ID is not a Number and expect a Bad-Request Return-Code")
  void getOneById_NOK_invalidId() throws Exception {
    restControllerWeb.perform(get("/api/persons/invalidNumber"))
                     .andExpect(status().isBadRequest());
  }

  @Test
  @DisplayName("Create a new Person and expect that it has been stored in the Database with a new ID generated by the JPA")
  @Transactional
  void create_OK() throws Exception {
    final Person person = objectMapper.readValue(
        restControllerWeb.perform(post("/api/persons")
            .contentType(APPLICATION_JSON_UTF8)
            .content(objectMapper.writeValueAsString(
                Person.builder()
                      .lastName("Stadler")
                      .firstName("Andrea")
                      .build())))
                         .andExpect(status().isCreated())
                         .andExpect(content().contentType(APPLICATION_JSON_UTF8))
                         .andExpect(jsonPath("id").isNotEmpty())
                         .andExpect(jsonPath("lastName").value(is("Stadler")))
                         .andExpect(jsonPath("firstName").value(is("Andrea")))
                         .andReturn()
                         .getResponse()
                         .getContentAsString(),
        Person.class);
    entityManager.flush();
    assertThat(personRepository.findById(person.getId()))
        .isPresent()
        .isEqualTo(Optional.of(person));
  }

  @Test
  @DisplayName("Update the Person with ID 1 and expect its Name is Fabian Stadler (returned by the Response and inside the Database)")
  @Transactional
  void update_OK() throws Exception {
    final Person person = objectMapper.readValue(
        restControllerWeb.perform(put("/api/persons/1")
            .contentType(APPLICATION_JSON_UTF8)
            .content(objectMapper.writeValueAsString(
                Person.builder()
                      .lastName("Stadler")
                      .firstName("Fabian")
                      .build())))
                         .andExpect(status().isOk())
                         .andExpect(content().contentType(APPLICATION_JSON_UTF8))
                         .andExpect(jsonPath("id").value(is(1)))
                         .andExpect(jsonPath("lastName").value(is("Stadler")))
                         .andExpect(jsonPath("firstName").value(is("Fabian")))
                         .andReturn()
                         .getResponse()
                         .getContentAsString(),
        Person.class);
    entityManager.flush();
    assertThat(personRepository.findById(1L))
        .isPresent()
        .isEqualTo(Optional.of(person));
  }

  @Test
  @DisplayName("Update a non-existent Person with ID 9999999999 and expect, that it hasn't been found")
  void update_NOK_notFound() throws Exception {
    restControllerWeb.perform(put("/api/persons/9999999999")
        .contentType(APPLICATION_JSON_UTF8)
        .content(objectMapper.writeValueAsString(
            Person.builder()
                  .lastName("Mustermann")
                  .firstName("Max")
                  .build())))
                     .andExpect(status().isNotFound());
  }

  @Test
  @DisplayName("Delete the Person with ID 1 and expect that this Person has been removed from the Database")
  @Transactional
  void delete_OK() throws Exception {
    assertThat(personRepository.findById(1L)).isPresent();
    restControllerWeb.perform(delete("/api/persons/1"))
                     .andExpect(status().isNoContent());
    assertThat(personRepository.findById(1L)).isNotPresent();
  }

  @Test
  @DisplayName("Delete the non-existent Person with ID 9999999999 and expect that it hasn't been found")
  void delete_NOK_notFound() throws Exception {
    restControllerWeb.perform(delete("/api/persons/9999999999"))
                     .andExpect(status().isNotFound());
  }
}
